version: '3.8'

services:
  todolist-app:
    container_name: todolist-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public

